ktor:
  application:
    modules:
      - com.coffeeshop.ApplicationKt.module
  deployment:
    port: 8080
storage:
  driver: "org.postgresql.Driver"
  jdbcURL: "jdbc:postgresql://localhost:5432/order_service"
  user: "postgres"
  password: "password"
  mongo:
    uri: "mongodb://localhost:27017/?maxPoolSize=20&w=majority"
    database: "order_service"

kafka:
  host: "localhost:9092"